# This document stores information about videos to be pulled by frameposter.py
# It is necessary to have accurate information here so that frameposter.py works correctly.
# I'd recommend editing this with videos.setup.py, but you may edit this file directly if necessary (e.g. need to rename a file in the directory)

# Quick glossary of every variable here:
# filename - Video filename
# videoname - Name of video (for text and alt text)
# frames - Number of frames in the video
# framerate - Framerate, provided as a number or a fraction (fraction is more accurate, but any possible discrepancies wwould only happen for extremely long videos)
# hdr - Whether the video uses HDR or not
# croptb - The total number of pixels to crop from the top and bottom combined (for letterboxed videos)
# croplr - The total number of pixels to crop from the left and right combined (for pillarboxed videos)
# nopost - Ranges of frames where the script should not post from. Should be a list of nested lists consisting of [start, end] frames in range of frames that should not be posted, inclusive.
# tags - List of tags to post the video with on microblog sites such as Tumblr and Cohost. Should be safe to leave blank if you just leave the [] behind.
# 
# The following is an example of a toml file that might be used on my own bot:
#
#
#
# [0]
# filename = 'movie0.mkv'
# videoname = "Into The Spider-Verse"
# frames = 168072
# framerate = '24000/1001'
# hdr = true
# croptb = 552
# croplr = 0
# nopost = [[1,1538], [1593,1638], [1710,1757],[1789,1829],[151630,151693],[156011,166125],[167856,168072]]
# tags = ['Spider-Man', 'Spider-Verse', 'Spider-Man: Into the Spider-Verse', 'Into the Spider-Verse']
# [1]
# filename = 'nbc.mp4'
# videoname = "NBC Mystery Movie"
# frames = 146856
# framerate = '23.976'
# hdr = false
# croptb = 0
# croplr = 0
# nopost = []
# tags = []
#
# NOTE: When invoking frameposter.py, you'll be using the value in the brackets as your argument to select a film.
[0]
filename = ''
videoname = ""
frames = 42
framerate = '24000/1001'
hdr = false
croptb = 0
croplr = 0
nopost = []
tags = []